[Subsystem]

[Aio]
  AIO /home/libxpdk/raid_test/disk1.img Aio0 4096
  AIO /home/libxpdk/raid_test/disk2.img Aio1 4096

[Raid]
  Name Raid1
  StripSize 64
  NumDevices 2
  RaidLevel 1
  Devices Aio0 Aio1

